### ISSUE TITLE
how to add the rmd templates into RStudio?

### ISSUE THREAD

**Issue by jianlianggao** [mikey-harper/example-rmd-templates#1]
Hi Mike,

A question please. How to add the rmd templates into RStudio?

Thanks,
BW,
Jianliang

**Comment by dr-harper** [comment]
Hi Jianliang,

I have added a README.md to the repository explaining this plus a bit more about how to use it.   See commit  95f758e3cead63966f0061fef0dc6a8d9cdc587f

But in summary you can install the package using:

```
# install.packages("devtools")
devtools::install_github("mikey-harper/example-rmd-templates")
```

Feel free to open any other issues: it is good to get the feedback.

**Comment by jianlianggao** [comment]
Hi Mike,

Thank you very much for the update.

users need to run `install.packages("curl") immediately after installing the devtools. Otherwise install_github will fail.

BW,
Jianliang

**Comment by dr-harper** [comment]
Curl should be automatically  installed when install devtools. It seems likely you are using an old version of R as this is unexpected behaviour.
